@Doctor_CLinic_API_HostAddress = https://localhost:7213

GET {{Doctor_CLinic_API_HostAddress}}/api/test/secure
Authorization: Bearer CfDJ8OVOACWzzAlFrjwTRyXAslTUodpLRukExWXnwxNEqUmg20LtRQeRbmhNUd0Y8fG0_ItXCYRwP6W7cGGikwoz6B3qqNXvp-xxBq9LxjReXmOTKx6henm23Ts_UAY87ezCcvbFgEGeGtR7Er5-_PRon65fx9iVL-SoN1xl9XEHXOysOdLMuBgp3AQ3UOoLyql04BYRBfD-hVUBpncvktXITRBvY1pvWuu-wuEYX2TLADFa_WFtyAFSGtX0RTWbOThkGjDDZgOM7tT1j1PVAqwzrRYsaJ13KSVbQTKqz4YqeutL31HjvK2cjn_oIBaPLrKDvtVa9D69HdBzB7Tzmnb5xj6goz0f0yfOgxWQS8_xyeyhhAa3pPMZVYlEI_tm36WnTO0gPx3hJwmm-Lqemgp3gFhUncAaCqAVIwincMQpBRcw2ncXFJW4ptSiUXacNEqHlMmh1HXGkdWU12TLw5XxbZrbawzLyL1jxgYDEegaaKAyvd7gJeDMbebMmZwiMDx_V7kyUBA9YtcVx30W8uq9bdg3blwGvgOkQaYLj-_fYx6WpL5w_JZ9QUdNmuwnEU4fQmDTjBu6Ptv6BPKZfZfI-RZYKoTT7vZf0KwMI5diPJtL6V2igoqsnifqxlvvL5NA9-TDju6fLqbJYGmPD_HP5doxHZUMleyBXjtmsV-nyR_heHBZpCSR6wrJZnocU6-6Tw
###

GET {{Doctor_CLinic_API_HostAddress}}/api/test/public

###
